/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Smart Inventory Design Tokens (Material You palette) ──
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-low": "#eff4ff",
        "inverse-surface": "#213145",
        "secondary-fixed": "#dae2fd",
        "tertiary-fixed": "#cce5ff",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#b4c5ff",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "surface-tint": "#0053db",
        "surface-variant": "#d3e4fe",
        "secondary-container": "#dae2fd",
        background: "#f8f9ff",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#00174b",
        "tertiary-container": "#0073ae",
        "on-tertiary-container": "#e7f2ff",
        tertiary: "#005a89",
        "on-surface-variant": "#434655",
        secondary: "#565e74",
        "tertiary-fixed-dim": "#93ccff",
        "on-secondary-fixed": "#131b2e",
        "primary-container": "#2563eb",
        "on-tertiary-fixed-variant": "#004b73",
        outline: "#737686",
        "on-error": "#ffffff",
        surface: "#f8f9ff",
        "on-primary-container": "#eeefff",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary": "#ffffff",
        "on-surface": "#0b1c30",
        "on-secondary-container": "#5c647a",
        "surface-bright": "#f8f9ff",
        "outline-variant": "#c3c6d7",
        "on-error-container": "#93000a",
        "on-background": "#0b1c30",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed": "#001d31",
        "primary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        primary: "#004ac6",
        "surface-container-lowest": "#ffffff",
        // ── Legacy brand tokens (keep for existing pages) ──
        brand: {
          cyan: "#00d2ff",
          blue: "#0072ff",
          deep: "#032030",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        margin: "1.5rem",
        "margin-mobile": "0.75rem",
        "gutter-dense": "0.5rem",
        gutter: "1rem",
      },
      fontFamily: {
        "body-default": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-medium": ["Inter", "sans-serif"],
        "body-sm-medium": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        title: ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-default": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "code-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        title: ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        display: ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-default": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "body-medium": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0", fontWeight: "400" }],
        "body-sm-medium": ["13px", { lineHeight: "18px", letterSpacing: "0", fontWeight: "500" }],
        "label-default": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
        "code-mono": ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "500" }],
      },
      keyframes: {
        fadeIn: { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        slideUp: { from: { opacity: "0", transform: "translateY(16px)" }, to: { opacity: "1", transform: "translateY(0)" } },
      },
      animation: {
        fadeIn: "fadeIn 0.2s ease-out",
        slideUp: "slideUp 0.25s ease-out",
      },
    },
  },
  plugins: [],
};
