#chỉnh localhost theo từng máy ( ở phần url)
#nhập DB user/ password
spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1435;databaseName=smart_inventory;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:smart_user}
    password: ${DB_PASSWORD:SmartPassword123!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET:development-only-secret-key-change-before-deployment-32bytes-minimum}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

logging:
  level:
    org.hibernate.SQL: debug
    org.flywaydb: debug
